### ISSUE TITLE
Social links

### ISSUE THREAD

**Issue by Guysbert** [nunopress/grav-theme-parallelism#3]
Hi there. Great theme, but I don't see how to configure the social links at the bottom. A quick advice would be nice. Thanks in advance.

**Comment by namaless** [comment]
https://github.com/nunopress/grav-theme-parallelism/blob/develop/parallelism.yaml#L5-L9

You need to add your social link, if you not have one, you can leave the string empty, example
    ""

**Comment by Guysbert** [comment]
I uncommented the part in the template. But it is good to know where the information comes from. Thank you for your answer.

**Comment by namaless** [comment]
After check the theme i have a update:
https://github.com/nunopress/grav-theme-parallelism/blob/develop/templates/default.html.twig#L96-L102

You need to remove every social link not used. You can add another social link following the font awesome icon class name.

**Comment by namaless** [comment]
Sorry but i ported this theme from another one design, so i don't remember every options :) Btw nice to know you are fine, thanks again to use grav and my projects :)
